### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by baurst** [aharley/track_check_repeat#1]
Hi,
first of all let me say thank you for the great work! :) I was thinking about trying it out, but I have noticed that there is no license included in the project. Without a license, the work is under exclusive copyright by default. Could you please add one? You could check out [choosealicense.com](https://choosealicense.com/) if you are unsure which license fits your needs.
Thank you very much.

**Comment by aharley** [comment]
Added MIT license. Thanks!
