### ISSUE TITLE
Clarification for the evaluation

### ISSUE THREAD

**Issue by ghost** [aharley/track_check_repeat#3]
Hi,
I have a few questions regarding your evaluation. 

1) In the readme file from this repository, it's mentioned that the testing has been done using sequences 0009-0010. However, in your code, the evaluation code uses sequences 0010-0011. Could you specify which sequence you evaluated your trained model on?

2) Was the quantitative result in object discovery from the paper produced using the sequence 0010-0011?

3) For the object discovery, did you evaluate your detector on all types of objects(e.g. cyclist, car, van, and pedestrian) except for 'DontCare' class in KITTI?

Thanks a lot for your work!

**Comment by aharley** [comment]
1. Good catch!

**Comment by aharley** [comment]
1. Good catch! You are right, we actually evaluate on 0010-0011, while pseudolabels are generated from 0000-0009. I will update the readme. 
2. Yes, the paper used the same split. 
3. Yes, all types of objects. In the paper I think it was only vehicles, but in this repo it's all categories (which is harder).
